#!/usr/bin/python
# Copyright 2016, Ryan Finnin Day <rday@finninday.net>
#
# nagios service check to determine jenkins queue health
# based on age of oldest job in queue and number of minions active
#
# Usage: check_nagios -w WARNMINUTES -c CRITMINUTES -j JENKINSURL
#                     -m MAXMINIONS -g MAXMERGEAGE -p MERGEPATTERN
#
# Returns: OK, WARN, or CRITCAL with status, ie:
# OK - Build queue is empty and 5 minions are active

from optparse import OptionParser
from datetime import datetime
import time
import jenkins
import os
import sys
import re

parser = OptionParser()
parser.add_option("-w", dest="warn", help="warn threshold")
parser.add_option("-c", dest="crit", help="crit threshold")
parser.add_option("-j", dest="jenkins_url", help="url of jenkins master")
parser.add_option("-m", dest="minion_cap", help="max concurrent minions")
parser.add_option("-g", dest="max_merge_age", help="max merge job duration")
parser.add_option("-p", dest="merge_job_pattern", help="pattern to match merge job")
(options, args) = parser.parse_args()

JENKINS_URL = options.jenkins_url
MINION_CAP = int(options.minion_cap)
NOWUNIX = int(time.time())
MAXMERGE = int(options.max_merge_age)
MERGEPAT = options.merge_job_pattern

# log in to jenkins master
jenkins_server = jenkins.Jenkins(JENKINS_URL)

# look at build queue
queue_info = jenkins_server.get_queue_info()
oldest = NOWUNIX
jobcount = len(queue_info)

# get minion list
nodes = jenkins_server.get_nodes()
nodecount = len(nodes)

# look through currently running builds to see if any
# merge jobs are stuck
builds = jenkins_server.get_running_builds()
for build in builds:
  build_name = build['name']
  build_number = build['number']
  build_info = jenkins_server.get_build_info(build_name, build_number)
  build_timestamp = build_info['timestamp']
  build_elapsed = (NOWUNIX - build_timestamp/1000)/60
  #print "build %s (%s) running for %d min" % (build_name, build_number, build_elapsed)
  if re.search(MERGEPAT, build_name):
    if build_elapsed > MAXMERGE:
      print "CRITICAL - merge job (%s - %s) has been running %d minutes" % (build_name, build_number, build_elapsed)
      sys.exit(2)

if (nodecount > (MINION_CAP - 5)):
    allminionsbusy = True
else:
    allminionsbusy = False

# get pending job info
if not queue_info:
    print "OK - Build queue is empty and %d minions are active" % nodecount
    sys.exit(0)
else:
    for job in queue_info:
        # jenkins inQueueSince is a millisecond timestamp
        # divide by 1000 to compare to standard unix timestamp
        jobtimestamp = job['inQueueSince']/1000
        if jobtimestamp < oldest:
            oldest = jobtimestamp
            oldjob = job

    minutes = (NOWUNIX - oldest) / 60
    name = oldjob['task']['name']

    if allminionsbusy:
        if minutes > int(options.crit):
            print "CRITICAL - oldest job (%s) is %d minutes old with %d minions active" % (name, minutes, nodecount)
            sys.exit(2)
        elif minutes > int(options.warn):
            print "WARNING - oldest job (%s) is %d minutes old with %d minions active" % (name, minutes, nodecount)
            sys.exit(1)
        elif jobcount > MINION_CAP * 5:
            print "WARNING - job queue is %d and minion cap is %d with %d minions active" % (jobcount, MINION_CAP, nodecount)
            sys.exit(1)
        else:
            print "OK - oldest job (%s) is %d minutes old and queue depth is %d with %d minions active" % (name, minutes, jobcount, nodecount)
            sys.exit(0)

    # if all minions are not busy...
    else:
        if jobcount > MINION_CAP * 5:
            print "WARNING - job queue is %d and minion cap is %d with %d minions active" % (jobcount, MINION_CAP, nodecount)
            sys.exit(1)
        else:
            print "OK - oldest job (%s) is %d minutes old and queue depth is %d with %d minions active" % (name, minutes, jobcount, nodecount)
            sys.exit(0)
